[package]
name = "dh-crack"
version = "0.1.0"
edition = "2024"

[lib]
name = "dh_crack"
path = "src/lib.rs"

[[bin]]
name = "dh-crack"
path = "src/main.rs"

[dependencies]
hex = "0.4"
num = "0.4"
thiserror = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
